workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: 16.2
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Build iOS app for physical device
        script: |
          xcodebuild build \
            -project mobile-ios/AnimalDot.xcodeproj \
            -scheme AnimalDot \
            -sdk iphoneos \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            -derivedDataPath $PWD/mobile-ios/build_data \
            -resolvePackageDependencies
      - name: Package into unsigned IPA
        script: |
          # Find the app folder dynamically from the project root
          APP_PATH=$(find $PWD/mobile-ios -name "*.app" -type d | head -n 1)
          
          # Stop the build if the app is missing
          if [ -z "$APP_PATH" ]; then
            echo "Error App file not found"
            exit 1
          fi
          
          # Create clean output directories
          mkdir -p $PWD/mobile-ios/outputs/Payload
          
          # Copy the found app file into the Payload folder
          cp -R "$APP_PATH" $PWD/mobile-ios/outputs/Payload/
          
          # Navigate into the outputs folder and zip it into an ipa
          cd $PWD/mobile-ios/outputs
          zip -r AnimalDot_Unsigned.ipa Payload/
    artifacts:
      - mobile-ios/outputs/*.ipa
    publishing:
      email:
        recipients:
          - j.edusei@icloud.com
        notify:
          success: true
          failure: true
